--
-- PostgreSQL database dump
--

-- Dumped from database version 13.12 (Debian 13.12-1.pgdg120+1)
-- Dumped by pg_dump version 13.12 (Debian 13.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: casbin_rule; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.casbin_rule (
    id bigint NOT NULL,
    ptype character varying(255) NOT NULL,
    v0 character varying(255) NOT NULL,
    v1 character varying(255) NOT NULL,
    v2 character varying(255) NOT NULL,
    v3 character varying(255) NOT NULL,
    v4 character varying(255) NOT NULL,
    v5 character varying(255) NOT NULL
);


ALTER TABLE public.casbin_rule OWNER TO hetu;

--
-- Name: casbin_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.casbin_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.casbin_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_department; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_department (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    create_time timestamp with time zone NOT NULL,
    status integer NOT NULL,
    parent_id bigint,
    sort integer NOT NULL
);


ALTER TABLE public.sys_department OWNER TO hetu;

--
-- Name: sys_department_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_dictdata; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_dictdata (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    status integer NOT NULL,
    sort integer NOT NULL,
    remark character varying(255),
    type_code character varying(255) NOT NULL
);


ALTER TABLE public.sys_dictdata OWNER TO hetu;

--
-- Name: sys_dictdata_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_dictdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dictdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_dicttype; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_dicttype (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    code character varying(255) NOT NULL,
    status integer NOT NULL,
    remark character varying(255)
);


ALTER TABLE public.sys_dicttype OWNER TO hetu;

--
-- Name: sys_dicttype_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_dicttype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dicttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_menu; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_menu (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    menu_type character varying(255) NOT NULL,
    path character varying(255),
    component character varying(255),
    sort integer NOT NULL,
    visible integer NOT NULL,
    icon character varying(255),
    redirect character varying(255),
    perm character varying(255),
    parent_id bigint
);


ALTER TABLE public.sys_menu OWNER TO hetu;

--
-- Name: sys_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_menu_roles; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_menu_roles (
    id bigint NOT NULL,
    menu_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.sys_menu_roles OWNER TO hetu;

--
-- Name: sys_menu_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_menu_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_menu_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_role; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_role (
    create_time timestamp with time zone NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    code character varying(50) NOT NULL,
    status integer NOT NULL,
    sort integer NOT NULL,
    update_time timestamp with time zone NOT NULL
);


ALTER TABLE public.sys_role OWNER TO hetu;

--
-- Name: sys_role_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_user; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_user (
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(100) NOT NULL,
    nickname character varying(255) NOT NULL,
    mobile character varying(20),
    gender_label character varying(10),
    avatar character varying(255),
    email character varying(254),
    status integer NOT NULL,
    create_time timestamp with time zone NOT NULL,
    dept_id bigint NOT NULL
);


ALTER TABLE public.sys_user OWNER TO hetu;

--
-- Name: sys_user_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_user_roles; Type: TABLE; Schema: public; Owner: hetu
--

CREATE TABLE public.sys_user_roles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.sys_user_roles OWNER TO hetu;

--
-- Name: sys_user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: hetu
--

ALTER TABLE public.sys_user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: casbin_rule; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.casbin_rule (id, ptype, v0, v1, v2, v3, v4, v5) FROM stdin;
309	p	admin	scada:site:permit:8	r			
310	p	tuhuayuan	scada:site:permit:8	r			
211	p	tuhuayuan	user:tuhuayuan:password	x			
212	p	tuhuayuan	user:tuhuayuan:me	x			
38	p	OPER	sys:user:add	x			
39	p	OPER	sys:user:edit	x			
40	p	OPER	sys:user:reset_pwd	x			
41	p	OPER	sys:user:delete	x			
42	p	OPER	sys:role:add	x			
43	p	OPER	sys:role:delete	x			
44	p	OPER	sys:role:edit	x			
45	p	OPER	sys:menu:add	x			
46	p	OPER	sys:menu:delete	x			
47	p	OPER	sys:menu:edit	x			
48	p	OPER	sys:dept:add	x			
49	p	OPER	sys:dept:edit	x			
50	p	OPER	sys:dept:delete	x			
51	p	OPER	sys:dict_type:add	x			
52	p	OPER	sys:dict_type:edit	x			
53	p	OPER	sys:dict_type:delete	x			
54	p	OPER	sys:dict:add	x			
55	p	OPER	sys:dict:delete	x			
56	p	OPER	sys:dict:edit	x			
233	p	admin	scada:site:permit:1	w			
234	p	tuhuayuan	scada:site:permit:1	w			
235	p	admin	scada:site:permit:1	r			
236	p	tuhuayuan	scada:site:permit:1	r			
262	p	ADMIN	scada:graph:add	x			
263	p	ADMIN	scada:graph:edit	x			
264	p	ADMIN	scada:graph:delete	x			
265	p	ADMIN	scada:site:add	x			
266	p	ADMIN	scada:site:edit	x			
267	p	ADMIN	scada:site:delete	x			
268	p	ADMIN	sys:user:add	x			
269	p	ADMIN	sys:user:edit	x			
270	p	ADMIN	sys:user:reset_pwd	x			
271	p	ADMIN	sys:user:delete	x			
272	p	ADMIN	sys:role:add	x			
273	p	ADMIN	sys:role:delete	x			
274	p	ADMIN	sys:role:edit	x			
275	p	ADMIN	sys:menu:add	x			
276	p	ADMIN	sys:menu:delete	x			
277	p	ADMIN	sys:menu:edit	x			
278	p	ADMIN	sys:dept:add	x			
279	p	ADMIN	sys:dept:edit	x			
280	p	ADMIN	sys:dept:delete	x			
281	p	ADMIN	sys:dict_type:add	x			
282	p	ADMIN	sys:dict_type:edit	x			
283	p	ADMIN	sys:dict_type:delete	x			
284	p	ADMIN	sys:dict:add	x			
285	p	ADMIN	sys:dict:delete	x			
286	p	ADMIN	sys:dict:edit	x			
287	p	ADMIN	scada:alert:info	x			
288	p	ADMIN	sys:user:info	x			
289	p	ADMIN	scada:module:info	x			
290	p	ADMIN	scada:site:info	x			
291	p	ADMIN	scada:module:add	x			
292	p	ADMIN	scada:module:edit	x			
293	p	ADMIN	scada:module:delete	x			
294	p	ADMIN	scada:variable:add	x			
295	p	ADMIN	scada:variable:delete	x			
296	p	ADMIN	scada:variable:read	x			
297	p	ADMIN	scada:variable:write	x			
298	p	ADMIN	scada:variable:edit	x			
299	p	ADMIN	scada:alert:add	x			
300	p	ADMIN	scada:alert:edit	x			
301	p	ADMIN	scada:alert:delete	x			
302	p	ADMIN	scada:collector:add	x			
303	p	ADMIN	scada:collector:edit	x			
304	p	ADMIN	scada:collector:delete	x			
305	p	SCADA	scada:alert:info	x			
306	p	SCADA	sys:user:info	x			
307	p	SCADA	scada:module:info	x			
308	p	SCADA	scada:site:info	x			
\.


--
-- Data for Name: sys_department; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_department (id, name, description, create_time, status, parent_id, sort) FROM stdin;
1	admin		2023-10-15 03:17:33.278905+00	1	\N	1
6	运营部		2023-10-17 12:07:00.186876+00	1	\N	2
8	运营中心		2023-11-18 13:58:02.191269+00	1	\N	1
\.


--
-- Data for Name: sys_dictdata; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_dictdata (id, name, value, status, sort, remark, type_code) FROM stdin;
1	男	1	1	1	\N	gender
2	女	2	1	2	\N	gender
4	未知	0	1	3	\N	gender
5	正常	1	1	1	\N	status
6	禁用	0	1	2	\N	status
\.


--
-- Data for Name: sys_dicttype; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_dicttype (id, name, code, status, remark) FROM stdin;
1	性别	gender	1	\N
2	状态	status	1	\N
\.


--
-- Data for Name: sys_menu; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_menu (id, name, menu_type, path, component, sort, visible, icon, redirect, perm, parent_id) FROM stdin;
0	根目录	CATALOG	\N	\N	1	1	\N	\N	\N	\N
69	组态添加	BUTTON		\N	1	1	document	\N	scada:graph:add	37
70	组态编辑	BUTTON	\N	\N	1	1	document	\N	scada:graph:edit	37
71	组态删除	BUTTON	\N	\N	1	1	document	\N	scada:graph:delete	37
72	站点新增	BUTTON	\N	\N	1	1	document	\N	scada:site:add	34
73	站点编辑	BUTTON	\N	\N	1	1	document	\N	scada:site:edit	34
74	站点删除	BUTTON	\N	\N	1	1	document	\N	scada:site:delete	34
8	系统管理	CATALOG	/system	Layout	1	1	system	/system/user	\N	0
10	用户新增	BUTTON		\N	1	1	\N	\N	sys:user:add	9
11	用户编辑	BUTTON	\N	\N	2	1	\N	\N	sys:user:edit	9
13	重置密码	BUTTON	\N	\N	4	1	\N	\N	sys:user:reset_pwd	9
12	用户删除	BUTTON	\N	\N	3	1	\N	\N	sys:user:delete	9
14	角色管理	MENU	role	system/role/index	2	1	role	\N	\N	8
15	角色新增	BUTTON		\N	1	1	\N	\N	sys:role:add	14
43	运营中心	CATALOG	/scada	dashboard/components/layouts/index	3	0	client	\N	\N	0
17	角色删除	BUTTON	\N	\N	3	1	\N	\N	sys:role:delete	14
16	角色编辑	BUTTON	\N	\N	2	1	\N	\N	sys:role:edit	14
18	菜单管理	MENU	menu	system/menu/index	3	1	menu	\N	\N	8
19	菜单新增	BUTTON		\N	1	1	\N	\N	sys:menu:add	18
20	菜单删除	BUTTON	\N	\N	2	1	\N	\N	sys:menu:delete	18
21	菜单编辑	BUTTON	\N	\N	3	1	\N	\N	sys:menu:edit	18
22	部门管理	MENU	dept	system/dept/index	4	1	tree	\N	\N	8
23	部门新增	BUTTON		\N	1	1	\N	\N	sys:dept:add	22
24	部门编辑	BUTTON	\N	\N	2	1	\N	\N	sys:dept:edit	22
25	部门删除	BUTTON	\N	\N	3	1	\N	\N	sys:dept:delete	22
26	字典管理	MENU	dict	system/dict/index	5	1	dict	\N	\N	8
27	字典类型新增	BUTTON		\N	1	1	\N	\N	sys:dict_type:add	26
28	字典类型编辑	BUTTON	\N	\N	2	1	\N	\N	sys:dict_type:edit	26
29	字典类型删除	BUTTON	\N	\N	3	1	\N	\N	sys:dict_type:delete	26
30	字典数据新增	BUTTON	\N	\N	4	1	\N	\N	sys:dict:add	26
32	字典数据删除	BUTTON	\N	\N	6	1	\N	\N	sys:dict:delete	26
31	字典数据编辑	BUTTON	\N	\N	5	1	\N	\N	sys:dict:edit	26
9	用户管理	MENU	user	system/user/index	1	1	user	\N	\N	8
75	预警信息	BUTTON	\N	\N	1	1	document	\N	scada:alert:info	48
34	站点管理	MENU	site	base/site/index	1	1	nested	\N	\N	33
35	模块管理	MENU	module	base/module/index	2	1	monitor	\N	\N	33
36	变量管理	MENU	variable	base/variable/index	3	1	tree	\N	\N	33
49	组态图	MENU	graph	dashboard/graph	3	0	client	\N	\N	43
48	站点地图	MENU	site	dashboard/site	4	0	guide	\N	\N	43
50	视频监控	MENU	video	dashboard/video	2	0	monitor	\N	\N	43
51	在线用户	MENU	user	dashboard/user	1	0	user	\N	\N	43
52	用户信息	BUTTON		\N	1	1	\N	\N	sys:user:info	51
53	模块信息	BUTTON	\N	\N	1	1	\N	\N	scada:module:info	48
54	站点信息	BUTTON	\N	\N	1	1	\N	\N	scada:site:info	48
33	运营管理	CATALOG	/manage	Layout	2	1	homepage	/base/site/index	\N	0
55	模块添加	BUTTON		\N	1	1	\N	\N	scada:module:add	35
56	模块编辑	BUTTON	\N	\N	1	1	\N	\N	scada:module:edit	35
57	模块删除	BUTTON	\N	\N	1	1	\N	\N	scada:module:delete	35
58	变量添加	BUTTON	\N	\N	1	1	\N	\N	scada:variable:add	36
60	变量删除	BUTTON	\N	\N	1	1	\N	\N	scada:variable:delete	36
61	变量读取	BUTTON	\N	\N	1	1	\N	\N	scada:variable:read	36
62	变量写入	BUTTON	\N	\N	1	1	\N	\N	scada:variable:write	36
59	变量修改	BUTTON	\N	\N	1	1	\N	\N	scada:variable:edit	36
63	变量预警添加	BUTTON	\N	\N	1	1	\N	\N	scada:alert:add	36
64	变量预警编辑	BUTTON	\N	\N	1	1	\N	\N	scada:alert:edit	36
65	变量预警删除	BUTTON	\N	\N	1	1	\N	\N	scada:alert:delete	36
66	模块收集器添加	BUTTON	\N	\N	1	1	\N	\N	scada:collector:add	35
67	模块收集器编辑	BUTTON	\N	\N	1	1	\N	\N	scada:collector:edit	35
68	模块收集器删除	BUTTON	\N	\N	1	1	\N	\N	scada:collector:delete	35
37	组态管理	MENU	graph	base/graph/index	4	1	document	\N	\N	33
\.


--
-- Data for Name: sys_menu_roles; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_menu_roles (id, menu_id, role_id) FROM stdin;
1	0	3
2	8	3
3	9	3
5	11	3
6	12	3
7	13	3
8	14	3
9	15	3
10	16	3
11	17	3
12	18	3
13	19	3
14	20	3
15	21	3
16	22	3
17	23	3
18	24	3
19	25	3
20	26	3
21	27	3
22	28	3
23	29	3
24	30	3
25	31	3
26	32	3
27	10	3
29	8	1
30	9	1
31	10	1
32	11	1
33	12	1
34	13	1
35	14	1
36	15	1
37	16	1
38	17	1
39	18	1
40	19	1
41	20	1
42	21	1
43	22	1
44	23	1
45	24	1
46	25	1
47	26	1
48	27	1
49	28	1
50	29	1
51	30	1
52	31	1
53	32	1
54	33	1
55	34	1
56	35	1
57	36	1
58	37	1
63	43	1
67	43	4
68	48	4
69	49	4
70	50	4
71	51	4
72	52	4
73	53	4
74	54	4
75	48	1
76	49	1
77	50	1
78	51	1
79	52	1
80	53	1
81	54	1
82	55	1
83	56	1
84	57	1
85	58	1
86	59	1
87	60	1
88	61	1
89	62	1
90	63	1
91	64	1
92	65	1
93	66	1
94	67	1
95	68	1
96	69	1
97	70	1
98	71	1
99	72	1
100	73	1
101	74	1
102	75	1
103	75	4
\.


--
-- Data for Name: sys_role; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_role (create_time, id, name, code, status, sort, update_time) FROM stdin;
2023-10-15 03:17:33.274149+00	1	管理员	ADMIN	1	1	2023-10-15 03:17:33.274169+00
2023-10-17 12:11:06.372692+00	3	操作员	OPER	1	1	2023-11-18 13:56:42.413265+00
2023-11-18 13:57:29.32035+00	4	运营系统人员	SCADA	1	1	2023-11-18 13:57:29.320367+00
\.


--
-- Data for Name: sys_user; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_user (id, username, password, nickname, mobile, gender_label, avatar, email, status, create_time, dept_id) FROM stdin;
1	admin	043f047ea9e6a33f0315b84753d715a803d43cc7	超级管理员	13879156403	1	\N	\N	1	2023-10-15 03:17:33.280681+00	6
3	tuhuayuan	d84b7bf9eec050a02edccf2cadf1533eb10ad3e1	涂华远	13879156403	1	\N	tuhuayuan@gmail.com	1	2023-11-16 13:49:19.940106+00	8
\.


--
-- Data for Name: sys_user_roles; Type: TABLE DATA; Schema: public; Owner: hetu
--

COPY public.sys_user_roles (id, user_id, role_id) FROM stdin;
1	1	1
5	3	4
\.


--
-- Name: casbin_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.casbin_rule_id_seq', 310, true);


--
-- Name: sys_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_department_id_seq', 8, true);


--
-- Name: sys_dictdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_dictdata_id_seq', 6, true);


--
-- Name: sys_dicttype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_dicttype_id_seq', 2, true);


--
-- Name: sys_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_menu_id_seq', 75, true);


--
-- Name: sys_menu_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_menu_roles_id_seq', 103, true);


--
-- Name: sys_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_role_id_seq', 4, true);


--
-- Name: sys_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_user_id_seq', 3, true);


--
-- Name: sys_user_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hetu
--

SELECT pg_catalog.setval('public.sys_user_roles_id_seq', 5, true);


--
-- Name: casbin_rule casbin_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.casbin_rule
    ADD CONSTRAINT casbin_rule_pkey PRIMARY KEY (id);


--
-- Name: sys_department sys_department_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_department
    ADD CONSTRAINT sys_department_pkey PRIMARY KEY (id);


--
-- Name: sys_dictdata sys_dictdata_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_dictdata
    ADD CONSTRAINT sys_dictdata_pkey PRIMARY KEY (id);


--
-- Name: sys_dicttype sys_dicttype_code_key; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_dicttype
    ADD CONSTRAINT sys_dicttype_code_key UNIQUE (code);


--
-- Name: sys_dicttype sys_dicttype_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_dicttype
    ADD CONSTRAINT sys_dicttype_pkey PRIMARY KEY (id);


--
-- Name: sys_menu sys_menu_perm_key; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu
    ADD CONSTRAINT sys_menu_perm_key UNIQUE (perm);


--
-- Name: sys_menu sys_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu
    ADD CONSTRAINT sys_menu_pkey PRIMARY KEY (id);


--
-- Name: sys_menu_roles sys_menu_roles_menu_id_role_id_76a2cc6c_uniq; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu_roles
    ADD CONSTRAINT sys_menu_roles_menu_id_role_id_76a2cc6c_uniq UNIQUE (menu_id, role_id);


--
-- Name: sys_menu_roles sys_menu_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu_roles
    ADD CONSTRAINT sys_menu_roles_pkey PRIMARY KEY (id);


--
-- Name: sys_role sys_role_code_key; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_role
    ADD CONSTRAINT sys_role_code_key UNIQUE (code);


--
-- Name: sys_role sys_role_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_role
    ADD CONSTRAINT sys_role_pkey PRIMARY KEY (id);


--
-- Name: sys_user sys_user_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT sys_user_pkey PRIMARY KEY (id);


--
-- Name: sys_user_roles sys_user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user_roles
    ADD CONSTRAINT sys_user_roles_pkey PRIMARY KEY (id);


--
-- Name: sys_user_roles sys_user_roles_user_id_role_id_f0e1dc00_uniq; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user_roles
    ADD CONSTRAINT sys_user_roles_user_id_role_id_f0e1dc00_uniq UNIQUE (user_id, role_id);


--
-- Name: sys_user sys_user_username_key; Type: CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT sys_user_username_key UNIQUE (username);


--
-- Name: sys_department_parent_id_e9cc6dd0; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_department_parent_id_e9cc6dd0 ON public.sys_department USING btree (parent_id);


--
-- Name: sys_dicttype_code_6e8aa8f0_like; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_dicttype_code_6e8aa8f0_like ON public.sys_dicttype USING btree (code varchar_pattern_ops);


--
-- Name: sys_menu_parent_id_84e9a06a; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_menu_parent_id_84e9a06a ON public.sys_menu USING btree (parent_id);


--
-- Name: sys_menu_perm_3c72ba48_like; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_menu_perm_3c72ba48_like ON public.sys_menu USING btree (perm varchar_pattern_ops);


--
-- Name: sys_menu_roles_menu_id_cd3a7c8c; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_menu_roles_menu_id_cd3a7c8c ON public.sys_menu_roles USING btree (menu_id);


--
-- Name: sys_menu_roles_role_id_637dfe24; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_menu_roles_role_id_637dfe24 ON public.sys_menu_roles USING btree (role_id);


--
-- Name: sys_role_code_d1f437e9_like; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_role_code_d1f437e9_like ON public.sys_role USING btree (code varchar_pattern_ops);


--
-- Name: sys_user_dept_id_aad432e7; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_user_dept_id_aad432e7 ON public.sys_user USING btree (dept_id);


--
-- Name: sys_user_roles_role_id_17e6bf1b; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_user_roles_role_id_17e6bf1b ON public.sys_user_roles USING btree (role_id);


--
-- Name: sys_user_roles_user_id_97eefe2f; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_user_roles_user_id_97eefe2f ON public.sys_user_roles USING btree (user_id);


--
-- Name: sys_user_username_cfae0fd2_like; Type: INDEX; Schema: public; Owner: hetu
--

CREATE INDEX sys_user_username_cfae0fd2_like ON public.sys_user USING btree (username varchar_pattern_ops);


--
-- Name: sys_department sys_department_parent_id_e9cc6dd0_fk_sys_department_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_department
    ADD CONSTRAINT sys_department_parent_id_e9cc6dd0_fk_sys_department_id FOREIGN KEY (parent_id) REFERENCES public.sys_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sys_menu sys_menu_parent_id_84e9a06a_fk_sys_menu_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu
    ADD CONSTRAINT sys_menu_parent_id_84e9a06a_fk_sys_menu_id FOREIGN KEY (parent_id) REFERENCES public.sys_menu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sys_menu_roles sys_menu_roles_menu_id_cd3a7c8c_fk_sys_menu_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu_roles
    ADD CONSTRAINT sys_menu_roles_menu_id_cd3a7c8c_fk_sys_menu_id FOREIGN KEY (menu_id) REFERENCES public.sys_menu(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sys_menu_roles sys_menu_roles_role_id_637dfe24_fk_sys_role_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_menu_roles
    ADD CONSTRAINT sys_menu_roles_role_id_637dfe24_fk_sys_role_id FOREIGN KEY (role_id) REFERENCES public.sys_role(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sys_user sys_user_dept_id_aad432e7_fk_sys_department_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT sys_user_dept_id_aad432e7_fk_sys_department_id FOREIGN KEY (dept_id) REFERENCES public.sys_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sys_user_roles sys_user_roles_role_id_17e6bf1b_fk_sys_role_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user_roles
    ADD CONSTRAINT sys_user_roles_role_id_17e6bf1b_fk_sys_role_id FOREIGN KEY (role_id) REFERENCES public.sys_role(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sys_user_roles sys_user_roles_user_id_97eefe2f_fk_sys_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hetu
--

ALTER TABLE ONLY public.sys_user_roles
    ADD CONSTRAINT sys_user_roles_user_id_97eefe2f_fk_sys_user_id FOREIGN KEY (user_id) REFERENCES public.sys_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

