version: '3'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - my_network

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hetu
      POSTGRES_PASSWORD: hetu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4:5
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: tuhuayuan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: hetu
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - 9090:9090
    command: 
      --enable-feature=promql-at-modifier
      --web.enable-admin-api
      --web.enable-lifecycle
      --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deploy/prometheus/include:/etc/prometheus/include
    networks:
      - my_network
  
  pushgateway:
    image: prom/pushgateway:v1.6.2
    ports:
      - 9091:9091
    networks:
      - my_network

networks:
  my_network:

volumes:
  redis_data:
  postgres_data:
