global:
  http_config:
    follow_redirects: true

route:
  receiver: alert_api
  group_by: ['module_number', 'variable_name', 'alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 55s

receivers:
  - name: alert_api
    webhook_configs:
      - send_resolved: true
        url: http://hetu-api:8000/api/scada/alert/notify
        max_alerts: 0
