# Generated by Django 4.2.23 on 2025-11-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0004_department_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('system', '系统'), ('task', '任务'), ('alert', '告警')], default='text', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('unread', '未读')], default='sent', max_length=20)),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '重要'), ('urgent', '紧急')], default='normal', max_length=20)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='sys.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='sys.user')),
            ],
            options={
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['receiver', '-create_time'], name='sys_message_receive_e85802_idx'), models.Index(fields=['receiver', 'status'], name='sys_message_receive_f75383_idx')],
            },
        ),
    ]
