# Generated by Django 4.2.23 on 2025-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0007_graph_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevideosource',
            name='source_type',
            field=models.CharField(choices=[('YS', '萤石'), ('VIM', '华为行业视频')], default='YS', max_length=100),
        ),
    ]
