# Generated by Django 4.2.23 on 2025-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0008_sitevideosource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='pulse',
            field=models.BooleanField(default=False),
        ),
    ]
