# Generated by Django 4.2.23 on 2025-09-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0009_variable_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevideosource',
            name='capture',
            field=models.TextField(null=True),
        ),
    ]
