# Generated by Django 4.2.23 on 2025-11-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0011_sitevideosource_capture_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_version', models.CharField(db_index=True, max_length=50)),
                ('target_version', models.CharField(db_index=True, max_length=50)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('checking', '检查中'), ('downloading', '下载中'), ('installing', '安装中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '取消')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=50, unique=True)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], db_index=True, max_length=20)),
                ('download_url', models.URLField(max_length=500)),
                ('signature', models.TextField()),
                ('release_notes', models.TextField(default='')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('force_update', models.BooleanField(default=False)),
                ('min_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('version', 'platform')},
            },
        ),
    ]
