# Generated by Django 4.2.23 on 2025-11-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0014_dashboardcard'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardcard',
            new_name='scada_dashb_site_id_c4604b_idx',
            old_name='scada_dash_site_id_123456_idx',
        ),
    ]
