# Generated by Django 4.2.23 on 2025-11-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0015_rename_scada_dash_site_id_123456_idx_scada_dashb_site_id_c4604b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
