# Generated by Django migration to remove unique constraint on AppUpdate.version

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0017_add_performance_indexes'),
    ]

    operations = [
        # 移除 version 字段的唯一约束
        # 因为 unique_together = [["version", "platform"]] 已经保证了唯一性
        # 允许同一个版本号在不同平台上存在
        migrations.AlterField(
            model_name='appupdate',
            name='version',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]

